/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApierrorApiError,
  ModelsCreateAttemptRequest,
  ModelsGetUserTaskAttemptsResponse,
} from '../models/index';
import {
    ApierrorApiErrorFromJSON,
    ApierrorApiErrorToJSON,
    ModelsCreateAttemptRequestFromJSON,
    ModelsCreateAttemptRequestToJSON,
    ModelsGetUserTaskAttemptsResponseFromJSON,
    ModelsGetUserTaskAttemptsResponseToJSON,
} from '../models/index';

export interface AttemptsGetRequest {
    taskId: number;
}

export interface AttemptsPostRequest {
    attempt: ModelsCreateAttemptRequest;
}

/**
 * 
 */
export class AttemptsApi extends runtime.BaseAPI {

    /**
     * Retrieves all attempts submitted by the authenticated user for a given task.
     * List user’s attempts for a specific task
     */
    async attemptsGetRaw(requestParameters: AttemptsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsGetUserTaskAttemptsResponse>>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling attemptsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['taskId'] != null) {
            queryParameters['taskId'] = requestParameters['taskId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/attempts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsGetUserTaskAttemptsResponseFromJSON));
    }

    /**
     * Retrieves all attempts submitted by the authenticated user for a given task.
     * List user’s attempts for a specific task
     */
    async attemptsGet(requestParameters: AttemptsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsGetUserTaskAttemptsResponse>> {
        const response = await this.attemptsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submits a new code attempt for execution against a task’s test cases.
     * Create a new attempt
     */
    async attemptsPostRaw(requestParameters: AttemptsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['attempt'] == null) {
            throw new runtime.RequiredError(
                'attempt',
                'Required parameter "attempt" was null or undefined when calling attemptsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/attempts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsCreateAttemptRequestToJSON(requestParameters['attempt']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submits a new code attempt for execution against a task’s test cases.
     * Create a new attempt
     */
    async attemptsPost(requestParameters: AttemptsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.attemptsPostRaw(requestParameters, initOverrides);
    }

}
