/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApierrorApi,
  ApierrorApiError,
  AuthLoginPost200Response,
  DbUser,
  ModelsAuthUserDTO,
  ModelsCreateUserDTO,
} from '../models/index';
import {
    ApierrorApiFromJSON,
    ApierrorApiToJSON,
    ApierrorApiErrorFromJSON,
    ApierrorApiErrorToJSON,
    AuthLoginPost200ResponseFromJSON,
    AuthLoginPost200ResponseToJSON,
    DbUserFromJSON,
    DbUserToJSON,
    ModelsAuthUserDTOFromJSON,
    ModelsAuthUserDTOToJSON,
    ModelsCreateUserDTOFromJSON,
    ModelsCreateUserDTOToJSON,
} from '../models/index';

export interface AuthLoginPostRequest {
    credentials: ModelsAuthUserDTO;
}

export interface AuthRegisterPostRequest {
    user: ModelsCreateUserDTO;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Authenticates a user with email/username and password and returns a JWT upon success.
     * Authenticate user and get token
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
        if (requestParameters['credentials'] == null) {
            throw new runtime.RequiredError(
                'credentials',
                'Required parameter "credentials" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsAuthUserDTOToJSON(requestParameters['credentials']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Authenticates a user with email/username and password and returns a JWT upon success.
     * Authenticate user and get token
     */
    async authLoginPost(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginPost200Response> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Registers a new user with a username, email, and password.
     * Register a new user
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbUser>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsCreateUserDTOToJSON(requestParameters['user']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbUserFromJSON(jsonValue));
    }

    /**
     * Registers a new user with a username, email, and password.
     * Register a new user
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbUser> {
        const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
