/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApierrorApiError,
  DbTask,
  DbUpdateTaskParams,
  ModelsCreateTaskDTO,
  ModelsTaskByIdResponse,
} from '../models/index';
import {
    ApierrorApiErrorFromJSON,
    ApierrorApiErrorToJSON,
    DbTaskFromJSON,
    DbTaskToJSON,
    DbUpdateTaskParamsFromJSON,
    DbUpdateTaskParamsToJSON,
    ModelsCreateTaskDTOFromJSON,
    ModelsCreateTaskDTOToJSON,
    ModelsTaskByIdResponseFromJSON,
    ModelsTaskByIdResponseToJSON,
} from '../models/index';

export interface TasksGetRequest {
    title?: string;
    topics?: Array<number>;
    difficulties?: Array<number>;
    sort?: TasksGetSortEnum;
    limit?: number;
    offset?: number;
}

export interface TasksIdDeleteRequest {
    id: number;
}

export interface TasksIdGetRequest {
    id: number;
}

export interface TasksIdPutRequest {
    id: number;
    task: DbUpdateTaskParams;
}

export interface TasksPostRequest {
    task: ModelsCreateTaskDTO;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of tasks based on optional filters.
     * List tasks
     */
    async tasksGetRaw(requestParameters: TasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DbTask>>> {
        const queryParameters: any = {};

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        if (requestParameters['topics'] != null) {
            queryParameters['topics'] = requestParameters['topics']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['difficulties'] != null) {
            queryParameters['difficulties'] = requestParameters['difficulties']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DbTaskFromJSON));
    }

    /**
     * Retrieves a list of tasks based on optional filters.
     * List tasks
     */
    async tasksGet(requestParameters: TasksGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DbTask>> {
        const response = await this.tasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a task by ID.
     * Delete task
     */
    async tasksIdDeleteRaw(requestParameters: TasksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling tasksIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a task by ID.
     * Delete task
     */
    async tasksIdDelete(requestParameters: TasksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tasksIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a single task by its ID.
     * Get task by ID
     */
    async tasksIdGetRaw(requestParameters: TasksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsTaskByIdResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling tasksIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsTaskByIdResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a single task by its ID.
     * Get task by ID
     */
    async tasksIdGet(requestParameters: TasksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsTaskByIdResponse> {
        const response = await this.tasksIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing task\'s details by ID.
     * Update task
     */
    async tasksIdPutRaw(requestParameters: TasksIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling tasksIdPut().'
            );
        }

        if (requestParameters['task'] == null) {
            throw new runtime.RequiredError(
                'task',
                'Required parameter "task" was null or undefined when calling tasksIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DbUpdateTaskParamsToJSON(requestParameters['task']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates an existing task\'s details by ID.
     * Update task
     */
    async tasksIdPut(requestParameters: TasksIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tasksIdPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates a new task with the provided details.
     * Create a new task
     */
    async tasksPostRaw(requestParameters: TasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbTask>> {
        if (requestParameters['task'] == null) {
            throw new runtime.RequiredError(
                'task',
                'Required parameter "task" was null or undefined when calling tasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsCreateTaskDTOToJSON(requestParameters['task']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbTaskFromJSON(jsonValue));
    }

    /**
     * Creates a new task with the provided details.
     * Create a new task
     */
    async tasksPost(requestParameters: TasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbTask> {
        const response = await this.tasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const TasksGetSortEnum = {
    Name: 'name',
    Difficulty: 'difficulty',
    Score: 'score'
} as const;
export type TasksGetSortEnum = typeof TasksGetSortEnum[keyof typeof TasksGetSortEnum];
