/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApierrorApiError,
  DbTaskTestCase,
  ModelsNewTestCaseReq,
} from '../models/index';
import {
    ApierrorApiErrorFromJSON,
    ApierrorApiErrorToJSON,
    DbTaskTestCaseFromJSON,
    DbTaskTestCaseToJSON,
    ModelsNewTestCaseReqFromJSON,
    ModelsNewTestCaseReqToJSON,
} from '../models/index';

export interface TestCasesIdUploadPostRequest {
    id: number;
    type: string;
    file: Blob;
}

export interface TestCasesPostRequest {
    testCase: ModelsNewTestCaseReq;
}

/**
 * 
 */
export class TestCasesApi extends runtime.BaseAPI {

    /**
     * Uploads input/output file for a test case
     * Upload test case file
     */
    async testCasesIdUploadPostRaw(requestParameters: TestCasesIdUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling testCasesIdUploadPost().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling testCasesIdUploadPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling testCasesIdUploadPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/test-cases/{id}/upload`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Uploads input/output file for a test case
     * Upload test case file
     */
    async testCasesIdUploadPost(requestParameters: TestCasesIdUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testCasesIdUploadPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates a new test case for a task
     * Create a new test case
     */
    async testCasesPostRaw(requestParameters: TestCasesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbTaskTestCase>> {
        if (requestParameters['testCase'] == null) {
            throw new runtime.RequiredError(
                'testCase',
                'Required parameter "testCase" was null or undefined when calling testCasesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/test-cases`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsNewTestCaseReqToJSON(requestParameters['testCase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbTaskTestCaseFromJSON(jsonValue));
    }

    /**
     * Creates a new test case for a task
     * Create a new test case
     */
    async testCasesPost(requestParameters: TestCasesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbTaskTestCase> {
        const response = await this.testCasesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
