/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApierrorApiError,
  DbTopic,
} from '../models/index';
import {
    ApierrorApiErrorFromJSON,
    ApierrorApiErrorToJSON,
    DbTopicFromJSON,
    DbTopicToJSON,
} from '../models/index';

/**
 * 
 */
export class TopicsApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of tasks based on optional filters.
     * List tasks
     */
    async topicsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DbTopic>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/topics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DbTopicFromJSON));
    }

    /**
     * Retrieves a list of tasks based on optional filters.
     * List tasks
     */
    async topicsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DbTopic>> {
        const response = await this.topicsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Adds new topic by its alias
     * Add Topics
     */
    async topicsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbTopic>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/topics`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbTopicFromJSON(jsonValue));
    }

    /**
     * Adds new topic by its alias
     * Add Topics
     */
    async topicsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbTopic> {
        const response = await this.topicsPostRaw(initOverrides);
        return await response.value();
    }

}
