/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApierrorApiError,
  DbGetUsersLeaderboardRow,
} from '../models/index';
import {
    ApierrorApiErrorFromJSON,
    ApierrorApiErrorToJSON,
    DbGetUsersLeaderboardRowFromJSON,
    DbGetUsersLeaderboardRowToJSON,
} from '../models/index';

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Users leaderboard
     * Users leaderboard
     */
    async leaderboardGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DbGetUsersLeaderboardRow>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leaderboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DbGetUsersLeaderboardRowFromJSON));
    }

    /**
     * Users leaderboard
     * Users leaderboard
     */
    async leaderboardGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DbGetUsersLeaderboardRow>> {
        const response = await this.leaderboardGetRaw(initOverrides);
        return await response.value();
    }

}
