services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: rankode_db
    ports:
      - "5432:5432"
    networks:
      - rankode
    environment:
      POSTGRES_DB: rankode
      POSTGRES_USER: rankode
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - "/home/ferret/containers/rankode/postgres:/var/lib/postgresql/data"
  
  rabbitmq:
    image: "rabbitmq:management-alpine"
    restart: unless-stopped
    container_name: rankode_mq
    ports:
      - 16672:15672
      - 6672:5672
    networks:
      - rankode
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
  
  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: rankode_seaweedfs_master
    restart: unless-stopped
    ports:
      - "9333:9333"
    networks:
      - rankode
    volumes:
      - /home/ferret/containers/rankode/seaweedfs/master:/data
    command: 'master -ip=seaweedfs-master -ip.bind=0.0.0.0 -mdir=/data'

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: rankode_seaweedfs_volume
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - rankode
    volumes:
      - /home/ferret/containers/rankode/seaweedfs/volume:/data
    command: 'volume -mserver="seaweedfs-master:9333" -ip=seaweedfs-volume -ip.bind=0.0.0.0 -dir=/data -port=8080'
    depends_on:
      - seaweedfs-master

  seaweedfs-filer:
    image: chrislusf/seaweedfs
    container_name: rankode_seaweedfs_filer
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - rankode
    command: 'filer -master="seaweedfs-master:9333" -ip=seaweedfs-filer -ip.bind=0.0.0.0'
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume

  seaweedfs-s3:
    image: chrislusf/seaweedfs
    container_name: rankode_seaweedfs_s3
    restart: unless-stopped
    ports:
      - "8333:8333"
    networks:
      - rankode
    volumes:
      - ./seaweedfs-s3.conf:/etc/seaweedfs/s3.conf:ro
    command: 's3 -filer="seaweedfs-filer:8888" -ip.bind=0.0.0.0 -port=8333 -config=/etc/seaweedfs/s3.conf'
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
      - seaweedfs-filer
  
  backend:
    build: .
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_started
      seaweedfs-s3:
        condition: service_started
    restart: unless-stopped
    container_name: rankode_backend
    ports:
      - 4000:4000
    networks:
      - rankode
    env_file:
      - .env
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rankode.entrypoints=https"
      - "traefik.http.routers.rankode.rule=Host(`rankode.tech`)"
      - "traefik.http.routers.rankode.tls=true"
      - "traefik.http.routers.rankode.tls.certresolver=letsencrypt"

networks:
  rankode:
