services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: rankode_db
    ports:
      - "5432:5432"
    networks:
      - rankode
    environment:
      POSTGRES_DB: rankode
      POSTGRES_USER: rankode
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - "/home/ferret/containers/rankode/postgres:/var/lib/postgresql/data"
  
  rabbitmq:
    image: "rabbitmq:management-alpine"
    restart: unless-stopped
    container_name: rankode_mq
    ports:
      - 16672:15672
      - 6672:5672
    networks:
      - rankode
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
  
  minio:
    image: quay.io/minio/minio
    container_name: minio_rankode
    restart: unless-stopped
    ports:
        - 9000:9000
        - 9001:9001
    networks:
      - rankode
    volumes:
        - /home/ferret/containers/rankode/:/data
    environment:
        MINIO_ROOT_USER: ${MINIO_LOGIN}
        MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
  
  backend:
    build: .
    depends_on:
      - rabbitmq
      - db
      - minio
    restart: unless-stopped
    container_name: rankode_backend
    ports:
      - 4000:4000
    networks:
      - rankode
    env_file:
      - .env
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rankode.entrypoints=https"
      - "traefik.http.routers.rankode.rule=Host(`rankode.tech`)"
      - "traefik.http.routers.rankode.tls=true"
      - "traefik.http.routers.rankode.tls.certresolver=letsencrypt"

networks:
  rankode: