// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssignmentSubmissions = `-- name: CountAssignmentSubmissions :one
SELECT COUNT(*) FROM attempts WHERE assignment_id = $1::int
`

func (q *Queries) CountAssignmentSubmissions(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentSubmissions, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsWhoFinishedAssignment = `-- name: CountStudentsWhoFinishedAssignment :one
SELECT COUNT(*) 
FROM (
    SELECT a.user_id
    FROM attempts a
    WHERE a.assignment_id = $1::int AND a.attempt_status = 0
    GROUP BY a.user_id
    HAVING COUNT(DISTINCT a.task_id) >= (
        SELECT COUNT(*) FROM assignment_tasks WHERE assignment_id = $1::int
    )
) AS finished_students
`

func (q *Queries) CountStudentsWhoFinishedAssignment(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsWhoFinishedAssignment, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsWhoStartedAssignment = `-- name: CountStudentsWhoStartedAssignment :one
SELECT COUNT(DISTINCT user_id) FROM attempts WHERE assignment_id = $1::int
`

func (q *Queries) CountStudentsWhoStartedAssignment(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsWhoStartedAssignment, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (course_id, title, description, start_date, due_date, max_attempts_per_task, group_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, course_id, title, description, start_date, due_date, max_attempts_per_task, created_at, updated_at, group_id
`

type CreateAssignmentParams struct {
	CourseID           int32            `json:"course_id"`
	Title              string           `json:"title"`
	Description        pgtype.Text      `json:"description"`
	StartDate          pgtype.Timestamp `json:"start_date"`
	DueDate            pgtype.Timestamp `json:"due_date"`
	MaxAttemptsPerTask pgtype.Int4      `json:"max_attempts_per_task"`
	GroupID            pgtype.Int4      `json:"group_id"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.DueDate,
		arg.MaxAttemptsPerTask,
		arg.GroupID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.MaxAttemptsPerTask,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAssignment, id)
	return err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, course_id, title, description, start_date, due_date, max_attempts_per_task, created_at, updated_at, group_id FROM assignments WHERE id = $1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id int32) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.MaxAttemptsPerTask,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getAssignmentWithTasks = `-- name: GetAssignmentWithTasks :one
SELECT 
    a.id, a.course_id, a.title, a.description, a.start_date, a.due_date, a.max_attempts_per_task, a.created_at, a.updated_at, a.group_id,
    json_agg(
        json_build_object(
            'task_id', at.task_id,
            'order_index', at.order_index,
            'weight', at.weight
        ) ORDER BY at.order_index
    ) as tasks
FROM assignments a
LEFT JOIN assignment_tasks at ON a.id = at.assignment_id
WHERE a.id = $1
GROUP BY a.id
`

type GetAssignmentWithTasksRow struct {
	ID                 int32            `json:"id"`
	CourseID           int32            `json:"course_id"`
	Title              string           `json:"title"`
	Description        pgtype.Text      `json:"description"`
	StartDate          pgtype.Timestamp `json:"start_date"`
	DueDate            pgtype.Timestamp `json:"due_date"`
	MaxAttemptsPerTask pgtype.Int4      `json:"max_attempts_per_task"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	GroupID            pgtype.Int4      `json:"group_id"`
	Tasks              []byte           `json:"tasks"`
}

func (q *Queries) GetAssignmentWithTasks(ctx context.Context, id int32) (GetAssignmentWithTasksRow, error) {
	row := q.db.QueryRow(ctx, getAssignmentWithTasks, id)
	var i GetAssignmentWithTasksRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.MaxAttemptsPerTask,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.Tasks,
	)
	return i, err
}

const listAssignmentsByCourse = `-- name: ListAssignmentsByCourse :many
SELECT id, course_id, title, description, start_date, due_date, max_attempts_per_task, created_at, updated_at, group_id FROM assignments WHERE course_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAssignmentsByCourse(ctx context.Context, courseID int32) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.DueDate,
			&i.MaxAttemptsPerTask,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsForStudent = `-- name: ListAssignmentsForStudent :many
SELECT a.id, a.course_id, a.title, a.description, a.start_date, a.due_date, a.max_attempts_per_task, a.created_at, a.updated_at, a.group_id FROM assignments a
JOIN enrollments e ON a.course_id = e.course_id
LEFT JOIN group_students gs ON a.group_id = gs.group_id AND e.user_id = gs.user_id
WHERE e.user_id = $1 
  AND (a.start_date IS NULL OR a.start_date <= CURRENT_TIMESTAMP)
  AND (a.group_id IS NULL OR gs.user_id IS NOT NULL)
ORDER BY a.due_date ASC NULLS LAST, a.created_at DESC
`

func (q *Queries) ListAssignmentsForStudent(ctx context.Context, userID int32) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForStudent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.DueDate,
			&i.MaxAttemptsPerTask,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :exec
UPDATE assignments 
SET title = $2, description = $3, start_date = $4, due_date = $5, 
    max_attempts_per_task = $6, group_id = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateAssignmentParams struct {
	ID                 int32            `json:"id"`
	Title              string           `json:"title"`
	Description        pgtype.Text      `json:"description"`
	StartDate          pgtype.Timestamp `json:"start_date"`
	DueDate            pgtype.Timestamp `json:"due_date"`
	MaxAttemptsPerTask pgtype.Int4      `json:"max_attempts_per_task"`
	GroupID            pgtype.Int4      `json:"group_id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error {
	_, err := q.db.Exec(ctx, updateAssignment,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.DueDate,
		arg.MaxAttemptsPerTask,
		arg.GroupID,
	)
	return err
}
