// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: assignment_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskToAssignment = `-- name: AddTaskToAssignment :exec
INSERT INTO assignment_tasks (assignment_id, task_id, order_index, weight)
VALUES ($1, $2, $3, $4)
ON CONFLICT (assignment_id, task_id) DO UPDATE
SET order_index = $3, weight = $4
`

type AddTaskToAssignmentParams struct {
	AssignmentID int32          `json:"assignment_id"`
	TaskID       int32          `json:"task_id"`
	OrderIndex   int32          `json:"order_index"`
	Weight       pgtype.Numeric `json:"weight"`
}

func (q *Queries) AddTaskToAssignment(ctx context.Context, arg AddTaskToAssignmentParams) error {
	_, err := q.db.Exec(ctx, addTaskToAssignment,
		arg.AssignmentID,
		arg.TaskID,
		arg.OrderIndex,
		arg.Weight,
	)
	return err
}

const countTasksInAssignment = `-- name: CountTasksInAssignment :one
SELECT COUNT(*) FROM assignment_tasks WHERE assignment_id = $1
`

func (q *Queries) CountTasksInAssignment(ctx context.Context, assignmentID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksInAssignment, assignmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAssignmentForTask = `-- name: GetAssignmentForTask :one
SELECT a.id, a.course_id, a.title, a.description, a.start_date, a.due_date, a.max_attempts_per_task, a.created_at, a.updated_at, a.group_id FROM assignments a
JOIN assignment_tasks at ON a.id = at.assignment_id
WHERE at.task_id = $1
LIMIT 1
`

func (q *Queries) GetAssignmentForTask(ctx context.Context, taskID int32) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentForTask, taskID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.MaxAttemptsPerTask,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getTasksForAssignment = `-- name: GetTasksForAssignment :many
SELECT t.id, t.user_id, t.title, t.description, t.difficulty, t.passes, t.score, t.topics, t.created_at, t.updated_at, t.course_id, t.is_public, at.order_index, at.weight
FROM tasks t
JOIN assignment_tasks at ON t.id = at.task_id
WHERE at.assignment_id = $1
ORDER BY at.order_index
`

type GetTasksForAssignmentRow struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"user_id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Difficulty  int32            `json:"difficulty"`
	Passes      int32            `json:"passes"`
	Score       float64          `json:"score"`
	Topics      []int32          `json:"topics"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	CourseID    pgtype.Int4      `json:"course_id"`
	IsPublic    bool             `json:"is_public"`
	OrderIndex  int32            `json:"order_index"`
	Weight      pgtype.Numeric   `json:"weight"`
}

func (q *Queries) GetTasksForAssignment(ctx context.Context, assignmentID int32) ([]GetTasksForAssignmentRow, error) {
	rows, err := q.db.Query(ctx, getTasksForAssignment, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksForAssignmentRow
	for rows.Next() {
		var i GetTasksForAssignmentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Passes,
			&i.Score,
			&i.Topics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseID,
			&i.IsPublic,
			&i.OrderIndex,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskFromAssignment = `-- name: RemoveTaskFromAssignment :exec
DELETE FROM assignment_tasks WHERE assignment_id = $1 AND task_id = $2
`

type RemoveTaskFromAssignmentParams struct {
	AssignmentID int32 `json:"assignment_id"`
	TaskID       int32 `json:"task_id"`
}

func (q *Queries) RemoveTaskFromAssignment(ctx context.Context, arg RemoveTaskFromAssignmentParams) error {
	_, err := q.db.Exec(ctx, removeTaskFromAssignment, arg.AssignmentID, arg.TaskID)
	return err
}

const updateTaskOrderAndWeight = `-- name: UpdateTaskOrderAndWeight :exec
UPDATE assignment_tasks
SET order_index = $3, weight = $4
WHERE assignment_id = $1 AND task_id = $2
`

type UpdateTaskOrderAndWeightParams struct {
	AssignmentID int32          `json:"assignment_id"`
	TaskID       int32          `json:"task_id"`
	OrderIndex   int32          `json:"order_index"`
	Weight       pgtype.Numeric `json:"weight"`
}

func (q *Queries) UpdateTaskOrderAndWeight(ctx context.Context, arg UpdateTaskOrderAndWeightParams) error {
	_, err := q.db.Exec(ctx, updateTaskOrderAndWeight,
		arg.AssignmentID,
		arg.TaskID,
		arg.OrderIndex,
		arg.Weight,
	)
	return err
}
