// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkFirstSuccessfulAttempt = `-- name: CheckFirstSuccessfulAttempt :one
SELECT EXISTS(SELECT id, user_id, task_id, language, code, attempt_status, error, running_time, memory, created_at, updated_at, assignment_id from attempts where user_id = $1 and task_id = $2 and attempt_status = $3 AND (assignment_id = $4 OR $4 IS NULL))
`

type CheckFirstSuccessfulAttemptParams struct {
	UserID        int32       `json:"user_id"`
	TaskID        int32       `json:"task_id"`
	AttemptStatus int32       `json:"attempt_status"`
	AssignmentID  pgtype.Int4 `json:"assignment_id"`
}

func (q *Queries) CheckFirstSuccessfulAttempt(ctx context.Context, arg CheckFirstSuccessfulAttemptParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFirstSuccessfulAttempt,
		arg.UserID,
		arg.TaskID,
		arg.AttemptStatus,
		arg.AssignmentID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts(user_id, task_id, language, code, attempt_status, assignment_id) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, task_id, language, code, attempt_status, error, running_time, memory, created_at, updated_at, assignment_id
`

type CreateAttemptParams struct {
	UserID        int32       `json:"user_id"`
	TaskID        int32       `json:"task_id"`
	Language      string      `json:"language"`
	Code          string      `json:"code"`
	AttemptStatus int32       `json:"attempt_status"`
	AssignmentID  pgtype.Int4 `json:"assignment_id"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.UserID,
		arg.TaskID,
		arg.Language,
		arg.Code,
		arg.AttemptStatus,
		arg.AssignmentID,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Language,
		&i.Code,
		&i.AttemptStatus,
		&i.Error,
		&i.RunningTime,
		&i.Memory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
	)
	return i, err
}

const getAttemptById = `-- name: GetAttemptById :one
SELECT id, user_id, task_id, language, code, attempt_status, error, running_time, memory, created_at, updated_at, assignment_id FROM attempts WHERE id = $1
`

func (q *Queries) GetAttemptById(ctx context.Context, id int64) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptById, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Language,
		&i.Code,
		&i.AttemptStatus,
		&i.Error,
		&i.RunningTime,
		&i.Memory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
	)
	return i, err
}

const getUserAttemptsByTask = `-- name: GetUserAttemptsByTask :many
SELECT id, user_id, task_id, language, code, attempt_status, error, running_time, memory, created_at, updated_at, assignment_id from attempts WHERE user_id = $1 and task_id = $2 AND (assignment_id = $3 OR $3 IS NULL) ORDER BY updated_at DESC
`

type GetUserAttemptsByTaskParams struct {
	UserID       int32       `json:"user_id"`
	TaskID       int32       `json:"task_id"`
	AssignmentID pgtype.Int4 `json:"assignment_id"`
}

func (q *Queries) GetUserAttemptsByTask(ctx context.Context, arg GetUserAttemptsByTaskParams) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, getUserAttemptsByTask, arg.UserID, arg.TaskID, arg.AssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Language,
			&i.Code,
			&i.AttemptStatus,
			&i.Error,
			&i.RunningTime,
			&i.Memory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttemptStatus = `-- name: UpdateAttemptStatus :exec
UPDATE attempts SET attempt_status = $1, running_time = $2, memory = $3, error = $4 WHERE id = $5
`

type UpdateAttemptStatusParams struct {
	AttemptStatus int32       `json:"attempt_status"`
	RunningTime   pgtype.Int4 `json:"running_time"`
	Memory        pgtype.Int4 `json:"memory"`
	Error         pgtype.Text `json:"error"`
	ID            int64       `json:"id"`
}

func (q *Queries) UpdateAttemptStatus(ctx context.Context, arg UpdateAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updateAttemptStatus,
		arg.AttemptStatus,
		arg.RunningTime,
		arg.Memory,
		arg.Error,
		arg.ID,
	)
	return err
}
