// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (teacher_id, name, description, join_code)
VALUES ($1, $2, $3, $4)
RETURNING id, teacher_id, name, description, join_code, created_at, updated_at
`

type CreateCourseParams struct {
	TeacherID   int32       `json:"teacher_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	JoinCode    string      `json:"join_code"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TeacherID,
		arg.Name,
		arg.Description,
		arg.JoinCode,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1 AND teacher_id = $2
`

type DeleteCourseParams struct {
	ID        int32 `json:"id"`
	TeacherID int32 `json:"teacher_id"`
}

func (q *Queries) DeleteCourse(ctx context.Context, arg DeleteCourseParams) error {
	_, err := q.db.Exec(ctx, deleteCourse, arg.ID, arg.TeacherID)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, teacher_id, name, description, join_code, created_at, updated_at FROM courses WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id int32) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByJoinCode = `-- name: GetCourseByJoinCode :one
SELECT id, teacher_id, name, description, join_code, created_at, updated_at FROM courses WHERE join_code = $1
`

func (q *Queries) GetCourseByJoinCode(ctx context.Context, joinCode string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByJoinCode, joinCode)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseWithStats = `-- name: GetCourseWithStats :one
SELECT 
    c.id, c.teacher_id, c.name, c.description, c.join_code, c.created_at, c.updated_at,
    COUNT(DISTINCT e.user_id) as student_count,
    COUNT(DISTINCT a.id) as assignment_count
FROM courses c
LEFT JOIN enrollments e ON c.id = e.course_id
LEFT JOIN assignments a ON c.id = a.course_id
WHERE c.id = $1
GROUP BY c.id
`

type GetCourseWithStatsRow struct {
	ID              int32            `json:"id"`
	TeacherID       int32            `json:"teacher_id"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	JoinCode        string           `json:"join_code"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	StudentCount    int64            `json:"student_count"`
	AssignmentCount int64            `json:"assignment_count"`
}

func (q *Queries) GetCourseWithStats(ctx context.Context, id int32) (GetCourseWithStatsRow, error) {
	row := q.db.QueryRow(ctx, getCourseWithStats, id)
	var i GetCourseWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentCount,
		&i.AssignmentCount,
	)
	return i, err
}

const listCoursesByTeacher = `-- name: ListCoursesByTeacher :many
SELECT id, teacher_id, name, description, join_code, created_at, updated_at FROM courses WHERE teacher_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCoursesByTeacher(ctx context.Context, teacherID int32) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesForStudent = `-- name: ListCoursesForStudent :many
SELECT c.id, c.teacher_id, c.name, c.description, c.join_code, c.created_at, c.updated_at FROM courses c
JOIN enrollments e ON c.id = e.course_id
WHERE e.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListCoursesForStudent(ctx context.Context, userID int32) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesForStudent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses 
SET name = $2, description = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND teacher_id = $4
`

type UpdateCourseParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	TeacherID   int32       `json:"teacher_id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.Exec(ctx, updateCourse,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TeacherID,
	)
	return err
}
