// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: enrollments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfEnrolled = `-- name: CheckIfEnrolled :one
SELECT EXISTS(SELECT 1 FROM enrollments WHERE course_id = $1 AND user_id = $2)
`

type CheckIfEnrolledParams struct {
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
}

func (q *Queries) CheckIfEnrolled(ctx context.Context, arg CheckIfEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfEnrolled, arg.CourseID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countStudentsInCourse = `-- name: CountStudentsInCourse :one
SELECT COUNT(*) FROM enrollments WHERE course_id = $1
`

func (q *Queries) CountStudentsInCourse(ctx context.Context, courseID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsInCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enrollStudent = `-- name: EnrollStudent :exec
INSERT INTO enrollments (course_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (course_id, user_id) DO UPDATE
SET role = $3
`

type EnrollStudentParams struct {
	CourseID int32       `json:"course_id"`
	UserID   int32       `json:"user_id"`
	Role     pgtype.Text `json:"role"`
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) error {
	_, err := q.db.Exec(ctx, enrollStudent, arg.CourseID, arg.UserID, arg.Role)
	return err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT course_id, user_id, enrolled_at, role FROM enrollments WHERE course_id = $1 AND user_id = $2
`

type GetEnrollmentParams struct {
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.CourseID, arg.UserID)
	var i Enrollment
	err := row.Scan(
		&i.CourseID,
		&i.UserID,
		&i.EnrolledAt,
		&i.Role,
	)
	return i, err
}

const listStudentsInCourse = `-- name: ListStudentsInCourse :many
SELECT u.id, u.username, u.email, u.password_hash, u.roles, u.elo, u.created_at, u.updated_at, e.enrolled_at, e.role as enrollment_role
FROM users u
JOIN enrollments e ON u.id = e.user_id
WHERE e.course_id = $1
ORDER BY e.enrolled_at DESC
`

type ListStudentsInCourseRow struct {
	ID             int32            `json:"id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	PasswordHash   string           `json:"password_hash"`
	Roles          int32            `json:"roles"`
	Elo            int32            `json:"elo"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	EnrolledAt     pgtype.Timestamp `json:"enrolled_at"`
	EnrollmentRole pgtype.Text      `json:"enrollment_role"`
}

func (q *Queries) ListStudentsInCourse(ctx context.Context, courseID int32) ([]ListStudentsInCourseRow, error) {
	rows, err := q.db.Query(ctx, listStudentsInCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsInCourseRow
	for rows.Next() {
		var i ListStudentsInCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Roles,
			&i.Elo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrolledAt,
			&i.EnrollmentRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unenrollStudent = `-- name: UnenrollStudent :exec
DELETE FROM enrollments WHERE course_id = $1 AND user_id = $2
`

type UnenrollStudentParams struct {
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
}

func (q *Queries) UnenrollStudent(ctx context.Context, arg UnenrollStudentParams) error {
	_, err := q.db.Exec(ctx, unenrollStudent, arg.CourseID, arg.UserID)
	return err
}
