// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: grades.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateGrade = `-- name: CreateOrUpdateGrade :one
INSERT INTO grades (assignment_id, task_id, user_id, grade, feedback, graded_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (assignment_id, task_id, user_id) DO UPDATE
SET grade = $4, feedback = $5, graded_by = $6, graded_at = CURRENT_TIMESTAMP
RETURNING id, assignment_id, task_id, user_id, grade, feedback, graded_by, graded_at
`

type CreateOrUpdateGradeParams struct {
	AssignmentID int32       `json:"assignment_id"`
	TaskID       int32       `json:"task_id"`
	UserID       int32       `json:"user_id"`
	Grade        int16       `json:"grade"`
	Feedback     pgtype.Text `json:"feedback"`
	GradedBy     pgtype.Int4 `json:"graded_by"`
}

func (q *Queries) CreateOrUpdateGrade(ctx context.Context, arg CreateOrUpdateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, createOrUpdateGrade,
		arg.AssignmentID,
		arg.TaskID,
		arg.UserID,
		arg.Grade,
		arg.Feedback,
		arg.GradedBy,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.TaskID,
		&i.UserID,
		&i.Grade,
		&i.Feedback,
		&i.GradedBy,
		&i.GradedAt,
	)
	return i, err
}

const deleteGrade = `-- name: DeleteGrade :exec
DELETE FROM grades WHERE id = $1
`

func (q *Queries) DeleteGrade(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGrade, id)
	return err
}

const getAverageGradeForAssignment = `-- name: GetAverageGradeForAssignment :one
SELECT AVG(grade)::numeric(3,2) as average_grade
FROM grades
WHERE assignment_id = $1
`

func (q *Queries) GetAverageGradeForAssignment(ctx context.Context, assignmentID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAverageGradeForAssignment, assignmentID)
	var average_grade pgtype.Numeric
	err := row.Scan(&average_grade)
	return average_grade, err
}

const getGrade = `-- name: GetGrade :one
SELECT id, assignment_id, task_id, user_id, grade, feedback, graded_by, graded_at FROM grades WHERE assignment_id = $1 AND task_id = $2 AND user_id = $3
`

type GetGradeParams struct {
	AssignmentID int32 `json:"assignment_id"`
	TaskID       int32 `json:"task_id"`
	UserID       int32 `json:"user_id"`
}

func (q *Queries) GetGrade(ctx context.Context, arg GetGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, getGrade, arg.AssignmentID, arg.TaskID, arg.UserID)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.TaskID,
		&i.UserID,
		&i.Grade,
		&i.Feedback,
		&i.GradedBy,
		&i.GradedAt,
	)
	return i, err
}

const getGradesForAssignment = `-- name: GetGradesForAssignment :many
SELECT g.id, g.assignment_id, g.task_id, g.user_id, g.grade, g.feedback, g.graded_by, g.graded_at, u.username as student_username, t.title as task_title
FROM grades g
JOIN users u ON g.user_id = u.id
JOIN tasks t ON g.task_id = t.id
WHERE g.assignment_id = $1
ORDER BY u.username, t.title
`

type GetGradesForAssignmentRow struct {
	ID              int32            `json:"id"`
	AssignmentID    int32            `json:"assignment_id"`
	TaskID          int32            `json:"task_id"`
	UserID          int32            `json:"user_id"`
	Grade           int16            `json:"grade"`
	Feedback        pgtype.Text      `json:"feedback"`
	GradedBy        pgtype.Int4      `json:"graded_by"`
	GradedAt        pgtype.Timestamp `json:"graded_at"`
	StudentUsername string           `json:"student_username"`
	TaskTitle       string           `json:"task_title"`
}

func (q *Queries) GetGradesForAssignment(ctx context.Context, assignmentID int32) ([]GetGradesForAssignmentRow, error) {
	rows, err := q.db.Query(ctx, getGradesForAssignment, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGradesForAssignmentRow
	for rows.Next() {
		var i GetGradesForAssignmentRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.TaskID,
			&i.UserID,
			&i.Grade,
			&i.Feedback,
			&i.GradedBy,
			&i.GradedAt,
			&i.StudentUsername,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentGradesForAssignment = `-- name: GetStudentGradesForAssignment :many
SELECT g.id, g.assignment_id, g.task_id, g.user_id, g.grade, g.feedback, g.graded_by, g.graded_at, t.title as task_title
FROM grades g
JOIN tasks t ON g.task_id = t.id
WHERE g.assignment_id = $1 AND g.user_id = $2
ORDER BY t.title
`

type GetStudentGradesForAssignmentParams struct {
	AssignmentID int32 `json:"assignment_id"`
	UserID       int32 `json:"user_id"`
}

type GetStudentGradesForAssignmentRow struct {
	ID           int32            `json:"id"`
	AssignmentID int32            `json:"assignment_id"`
	TaskID       int32            `json:"task_id"`
	UserID       int32            `json:"user_id"`
	Grade        int16            `json:"grade"`
	Feedback     pgtype.Text      `json:"feedback"`
	GradedBy     pgtype.Int4      `json:"graded_by"`
	GradedAt     pgtype.Timestamp `json:"graded_at"`
	TaskTitle    string           `json:"task_title"`
}

func (q *Queries) GetStudentGradesForAssignment(ctx context.Context, arg GetStudentGradesForAssignmentParams) ([]GetStudentGradesForAssignmentRow, error) {
	rows, err := q.db.Query(ctx, getStudentGradesForAssignment, arg.AssignmentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentGradesForAssignmentRow
	for rows.Next() {
		var i GetStudentGradesForAssignmentRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.TaskID,
			&i.UserID,
			&i.Grade,
			&i.Feedback,
			&i.GradedBy,
			&i.GradedAt,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentGradesForCourse = `-- name: GetStudentGradesForCourse :many
SELECT g.id, g.assignment_id, g.task_id, g.user_id, g.grade, g.feedback, g.graded_by, g.graded_at, a.title as assignment_title, t.title as task_title
FROM grades g
JOIN assignments a ON g.assignment_id = a.id
JOIN tasks t ON g.task_id = t.id
WHERE a.course_id = $1 AND g.user_id = $2
ORDER BY a.due_date, t.title
`

type GetStudentGradesForCourseParams struct {
	CourseID int32 `json:"course_id"`
	UserID   int32 `json:"user_id"`
}

type GetStudentGradesForCourseRow struct {
	ID              int32            `json:"id"`
	AssignmentID    int32            `json:"assignment_id"`
	TaskID          int32            `json:"task_id"`
	UserID          int32            `json:"user_id"`
	Grade           int16            `json:"grade"`
	Feedback        pgtype.Text      `json:"feedback"`
	GradedBy        pgtype.Int4      `json:"graded_by"`
	GradedAt        pgtype.Timestamp `json:"graded_at"`
	AssignmentTitle string           `json:"assignment_title"`
	TaskTitle       string           `json:"task_title"`
}

func (q *Queries) GetStudentGradesForCourse(ctx context.Context, arg GetStudentGradesForCourseParams) ([]GetStudentGradesForCourseRow, error) {
	rows, err := q.db.Query(ctx, getStudentGradesForCourse, arg.CourseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentGradesForCourseRow
	for rows.Next() {
		var i GetStudentGradesForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.TaskID,
			&i.UserID,
			&i.Grade,
			&i.Feedback,
			&i.GradedBy,
			&i.GradedAt,
			&i.AssignmentTitle,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
