// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"
)

const addStudentToGroup = `-- name: AddStudentToGroup :exec
INSERT INTO group_students (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddStudentToGroupParams struct {
	GroupID int32 `json:"group_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) error {
	_, err := q.db.Exec(ctx, addStudentToGroup, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (course_id, name)
VALUES ($1, $2)
RETURNING id, course_id, name, created_at
`

type CreateGroupParams struct {
	CourseID int32  `json:"course_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.CourseID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, course_id, name, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int32) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupsForStudent = `-- name: GetGroupsForStudent :many
SELECT g.id, g.course_id, g.name, g.created_at FROM groups g
JOIN group_students gs ON g.id = gs.group_id
WHERE gs.user_id = $1 AND g.course_id = $2
`

type GetGroupsForStudentParams struct {
	UserID   int32 `json:"user_id"`
	CourseID int32 `json:"course_id"`
}

func (q *Queries) GetGroupsForStudent(ctx context.Context, arg GetGroupsForStudentParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsForStudent, arg.UserID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByCourse = `-- name: ListGroupsByCourse :many
SELECT id, course_id, name, created_at FROM groups WHERE course_id = $1 ORDER BY name ASC
`

func (q *Queries) ListGroupsByCourse(ctx context.Context, courseID int32) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsInGroup = `-- name: ListStudentsInGroup :many
SELECT u.id, u.username, u.email, u.password_hash, u.roles, u.elo, u.created_at, u.updated_at FROM users u
JOIN group_students gs ON u.id = gs.user_id
WHERE gs.group_id = $1
ORDER BY u.username
`

func (q *Queries) ListStudentsInGroup(ctx context.Context, groupID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudentsInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Roles,
			&i.Elo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudentFromGroup = `-- name: RemoveStudentFromGroup :exec
DELETE FROM group_students WHERE group_id = $1 AND user_id = $2
`

type RemoveStudentFromGroupParams struct {
	GroupID int32 `json:"group_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) RemoveStudentFromGroup(ctx context.Context, arg RemoveStudentFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeStudentFromGroup, arg.GroupID, arg.UserID)
	return err
}
