// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package db

import (
	"context"
)

const languageExists = `-- name: LanguageExists :one
SELECT name from languages where 'name' = $1
`

func (q *Queries) LanguageExists(ctx context.Context, dollar_1 interface{}) (string, error) {
	row := q.db.QueryRow(ctx, languageExists, dollar_1)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT name from languages
`

func (q *Queries) ListLanguages(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
