// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lti.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLtiLink = `-- name: CreateLtiLink :exec
INSERT INTO lti_users (user_id, lti_subject, lti_issuer, lti_deployment_id)
VALUES ($1, $2, $3, $4)
`

type CreateLtiLinkParams struct {
	UserID          int32       `json:"user_id"`
	LtiSubject      string      `json:"lti_subject"`
	LtiIssuer       string      `json:"lti_issuer"`
	LtiDeploymentID pgtype.Text `json:"lti_deployment_id"`
}

func (q *Queries) CreateLtiLink(ctx context.Context, arg CreateLtiLinkParams) error {
	_, err := q.db.Exec(ctx, createLtiLink,
		arg.UserID,
		arg.LtiSubject,
		arg.LtiIssuer,
		arg.LtiDeploymentID,
	)
	return err
}

const getLtiUser = `-- name: GetLtiUser :one
SELECT id, user_id, lti_subject, lti_issuer, lti_deployment_id, created_at FROM lti_users WHERE lti_subject = $1 AND lti_issuer = $2
`

type GetLtiUserParams struct {
	LtiSubject string `json:"lti_subject"`
	LtiIssuer  string `json:"lti_issuer"`
}

func (q *Queries) GetLtiUser(ctx context.Context, arg GetLtiUserParams) (LtiUser, error) {
	row := q.db.QueryRow(ctx, getLtiUser, arg.LtiSubject, arg.LtiIssuer)
	var i LtiUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LtiSubject,
		&i.LtiIssuer,
		&i.LtiDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}
