// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	ID            int64            `json:"id"`
	UserID        int32            `json:"user_id"`
	TaskID        int32            `json:"task_id"`
	Language      string           `json:"language"`
	Code          string           `json:"code"`
	AttemptStatus int32            `json:"attempt_status"`
	Error         pgtype.Text      `json:"error"`
	RunningTime   pgtype.Int4      `json:"running_time"`
	Memory        pgtype.Int4      `json:"memory"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Language struct {
	Name string `json:"name"`
}

type Task struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"user_id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Difficulty  int32            `json:"difficulty"`
	Passes      int32            `json:"passes"`
	Score       float64          `json:"score"`
	Topics      []int32          `json:"topics"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type TaskTestCase struct {
	ID         int64            `json:"id"`
	TaskID     int32            `json:"task_id"`
	CaseOrder  int32            `json:"case_order"`
	InputFile  string           `json:"input_file"`
	OutputFile string           `json:"output_file"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Topic struct {
	ID         int32            `json:"id"`
	Name       string           `json:"name"`
	TasksCount int32            `json:"tasks_count"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Roles        int32            `json:"roles"`
	Elo          int32            `json:"elo"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
