// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOidcIdentity = `-- name: GetOidcIdentity :one
SELECT id, user_id, provider_name, subject, email, email_verified, created_at, updated_at FROM oidc_identities
WHERE provider_name = $1 AND subject = $2
`

type GetOidcIdentityParams struct {
	ProviderName string `json:"provider_name"`
	Subject      string `json:"subject"`
}

func (q *Queries) GetOidcIdentity(ctx context.Context, arg GetOidcIdentityParams) (OidcIdentity, error) {
	row := q.db.QueryRow(ctx, getOidcIdentity, arg.ProviderName, arg.Subject)
	var i OidcIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderName,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOidcProvider = `-- name: GetOidcProvider :one
SELECT name, issuer, client_id, client_secret, auth_url, token_url, jwks_url, redirect_url, frontend_redirect_url, scopes, allowed_domains, require_email_verified, created_at, updated_at FROM oidc_providers WHERE name = $1
`

func (q *Queries) GetOidcProvider(ctx context.Context, name string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOidcProvider, name)
	var i OidcProvider
	err := row.Scan(
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.JwksUrl,
		&i.RedirectUrl,
		&i.FrontendRedirectUrl,
		&i.Scopes,
		&i.AllowedDomains,
		&i.RequireEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOidcIdentity = `-- name: UpsertOidcIdentity :one
INSERT INTO oidc_identities (user_id, provider_name, subject, email, email_verified)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider_name, subject) DO UPDATE
SET email = EXCLUDED.email,
    email_verified = EXCLUDED.email_verified,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, provider_name, subject, email, email_verified, created_at, updated_at
`

type UpsertOidcIdentityParams struct {
	UserID        int32       `json:"user_id"`
	ProviderName  string      `json:"provider_name"`
	Subject       string      `json:"subject"`
	Email         pgtype.Text `json:"email"`
	EmailVerified bool        `json:"email_verified"`
}

func (q *Queries) UpsertOidcIdentity(ctx context.Context, arg UpsertOidcIdentityParams) (OidcIdentity, error) {
	row := q.db.QueryRow(ctx, upsertOidcIdentity,
		arg.UserID,
		arg.ProviderName,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
	)
	var i OidcIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderName,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOidcProvider = `-- name: UpsertOidcProvider :one
INSERT INTO oidc_providers (
    name,
    issuer,
    client_id,
    client_secret,
    auth_url,
    token_url,
    jwks_url,
    redirect_url,
    frontend_redirect_url,
    scopes,
    allowed_domains,
    require_email_verified
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (name) DO UPDATE
SET issuer = EXCLUDED.issuer,
    client_id = EXCLUDED.client_id,
    client_secret = EXCLUDED.client_secret,
    auth_url = EXCLUDED.auth_url,
    token_url = EXCLUDED.token_url,
    jwks_url = EXCLUDED.jwks_url,
    redirect_url = EXCLUDED.redirect_url,
    frontend_redirect_url = EXCLUDED.frontend_redirect_url,
    scopes = EXCLUDED.scopes,
    allowed_domains = EXCLUDED.allowed_domains,
    require_email_verified = EXCLUDED.require_email_verified,
    updated_at = CURRENT_TIMESTAMP
RETURNING name, issuer, client_id, client_secret, auth_url, token_url, jwks_url, redirect_url, frontend_redirect_url, scopes, allowed_domains, require_email_verified, created_at, updated_at
`

type UpsertOidcProviderParams struct {
	Name                 string      `json:"name"`
	Issuer               string      `json:"issuer"`
	ClientID             string      `json:"client_id"`
	ClientSecret         pgtype.Text `json:"client_secret"`
	AuthUrl              string      `json:"auth_url"`
	TokenUrl             string      `json:"token_url"`
	JwksUrl              string      `json:"jwks_url"`
	RedirectUrl          string      `json:"redirect_url"`
	FrontendRedirectUrl  string      `json:"frontend_redirect_url"`
	Scopes               []string    `json:"scopes"`
	AllowedDomains       []string    `json:"allowed_domains"`
	RequireEmailVerified bool        `json:"require_email_verified"`
}

func (q *Queries) UpsertOidcProvider(ctx context.Context, arg UpsertOidcProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, upsertOidcProvider,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.JwksUrl,
		arg.RedirectUrl,
		arg.FrontendRedirectUrl,
		arg.Scopes,
		arg.AllowedDomains,
		arg.RequireEmailVerified,
	)
	var i OidcProvider
	err := row.Scan(
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.JwksUrl,
		&i.RedirectUrl,
		&i.FrontendRedirectUrl,
		&i.Scopes,
		&i.AllowedDomains,
		&i.RequireEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
