// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	BanUser(ctx context.Context, id int32) error
	CheckFirstSuccessfulAttempt(ctx context.Context, arg CheckFirstSuccessfulAttemptParams) (bool, error)
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskTestCase(ctx context.Context, arg CreateTaskTestCaseParams) (TaskTestCase, error)
	CreateTopic(ctx context.Context, name string) (Topic, error)
	DeleteTask(ctx context.Context, id int32) error
	DeleteTaskTestCase(ctx context.Context, arg DeleteTaskTestCaseParams) error
	DeleteTopic(ctx context.Context, name string) error
	GetAttemptById(ctx context.Context, id int64) (Attempt, error)
	GetTaskById(ctx context.Context, id int32) (Task, error)
	GetTaskTestCases(ctx context.Context, taskID int32) ([]TaskTestCase, error)
	GetTestCaseByID(ctx context.Context, id int64) (TaskTestCase, error)
	GetUserAttemptsByTask(ctx context.Context, arg GetUserAttemptsByTaskParams) ([]Attempt, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUsersByEmailOrUsername(ctx context.Context, username string) (User, error)
	GetUsersLeaderboard(ctx context.Context, limit int32) ([]GetUsersLeaderboardRow, error)
	IncreaseTaskPasses(ctx context.Context, id int32) error
	IncreaseUserElo(ctx context.Context, arg IncreaseUserEloParams) error
	LanguageExists(ctx context.Context, dollar_1 interface{}) (string, error)
	ListLanguages(ctx context.Context) ([]string, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListTopicsByIDs(ctx context.Context, topicIds []int32) ([]Topic, error)
	NewUser(ctx context.Context, arg NewUserParams) (User, error)
	TopicsByName(ctx context.Context, name string) ([]Topic, error)
	UpdateAttemptStatus(ctx context.Context, arg UpdateAttemptStatusParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTopicsCounters(ctx context.Context, arg UpdateTopicsCountersParams) error
}

var _ Querier = (*Queries)(nil)
