// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, difficulty, passes, score, topics, course_id, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, description, difficulty, passes, score, topics, created_at, updated_at, course_id, is_public
`

type CreateTaskParams struct {
	UserID      int32       `json:"user_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Difficulty  int32       `json:"difficulty"`
	Passes      int32       `json:"passes"`
	Score       float64     `json:"score"`
	Topics      []int32     `json:"topics"`
	CourseID    pgtype.Int4 `json:"course_id"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Passes,
		arg.Score,
		arg.Topics,
		arg.CourseID,
		arg.IsPublic,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Passes,
		&i.Score,
		&i.Topics,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.IsPublic,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, user_id, title, description, difficulty, passes, score, topics, created_at, updated_at, course_id, is_public FROM tasks where id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Passes,
		&i.Score,
		&i.Topics,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseID,
		&i.IsPublic,
	)
	return i, err
}

const increaseTaskPasses = `-- name: IncreaseTaskPasses :exec
UPDATE tasks SET passes = passes + 1 WHERE id = $1
`

func (q *Queries) IncreaseTaskPasses(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, increaseTaskPasses, id)
	return err
}

const listPublicTasks = `-- name: ListPublicTasks :many
SELECT id, user_id, title, description, difficulty, passes, score, topics, created_at, updated_at, course_id, is_public FROM tasks WHERE is_public = true ORDER BY created_at DESC
`

func (q *Queries) ListPublicTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listPublicTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Passes,
			&i.Score,
			&i.Topics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseID,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, difficulty, passes, score, topics, created_at, updated_at, course_id, is_public FROM tasks
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Passes,
			&i.Score,
			&i.Topics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseID,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCourse = `-- name: ListTasksByCourse :many
SELECT id, user_id, title, description, difficulty, passes, score, topics, created_at, updated_at, course_id, is_public FROM tasks WHERE course_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTasksByCourse(ctx context.Context, courseID pgtype.Int4) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Passes,
			&i.Score,
			&i.Topics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseID,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = $2, description = $3, difficulty = $4, passes = $5, score = $6, topics = $7, course_id = $8, is_public = $9, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskParams struct {
	ID          int32       `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Difficulty  int32       `json:"difficulty"`
	Passes      int32       `json:"passes"`
	Score       float64     `json:"score"`
	Topics      []int32     `json:"topics"`
	CourseID    pgtype.Int4 `json:"course_id"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Passes,
		arg.Score,
		arg.Topics,
		arg.CourseID,
		arg.IsPublic,
	)
	return err
}

const updateTaskCourseAndVisibility = `-- name: UpdateTaskCourseAndVisibility :exec
UPDATE tasks SET course_id = $2, is_public = $3 WHERE id = $1
`

type UpdateTaskCourseAndVisibilityParams struct {
	ID       int32       `json:"id"`
	CourseID pgtype.Int4 `json:"course_id"`
	IsPublic bool        `json:"is_public"`
}

func (q *Queries) UpdateTaskCourseAndVisibility(ctx context.Context, arg UpdateTaskCourseAndVisibilityParams) error {
	_, err := q.db.Exec(ctx, updateTaskCourseAndVisibility, arg.ID, arg.CourseID, arg.IsPublic)
	return err
}
