// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_cases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskTestCase = `-- name: CreateTaskTestCase :one
INSERT INTO task_test_cases(task_id, case_order, input_file, output_file) VALUES ($1, $2, $3, $4) RETURNING id, task_id, case_order, input_file, output_file, created_at, updated_at
`

type CreateTaskTestCaseParams struct {
	TaskID     int32  `json:"task_id"`
	CaseOrder  int32  `json:"case_order"`
	InputFile  string `json:"input_file"`
	OutputFile string `json:"output_file"`
}

func (q *Queries) CreateTaskTestCase(ctx context.Context, arg CreateTaskTestCaseParams) (TaskTestCase, error) {
	row := q.db.QueryRow(ctx, createTaskTestCase,
		arg.TaskID,
		arg.CaseOrder,
		arg.InputFile,
		arg.OutputFile,
	)
	var i TaskTestCase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CaseOrder,
		&i.InputFile,
		&i.OutputFile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskTestCase = `-- name: DeleteTaskTestCase :exec
UPDATE attempts SET attempt_status = $1, running_time = $2, memory = $3, error = $4 WHERE id = $5
`

type DeleteTaskTestCaseParams struct {
	AttemptStatus int32       `json:"attempt_status"`
	RunningTime   pgtype.Int4 `json:"running_time"`
	Memory        pgtype.Int4 `json:"memory"`
	Error         pgtype.Text `json:"error"`
	ID            int64       `json:"id"`
}

func (q *Queries) DeleteTaskTestCase(ctx context.Context, arg DeleteTaskTestCaseParams) error {
	_, err := q.db.Exec(ctx, deleteTaskTestCase,
		arg.AttemptStatus,
		arg.RunningTime,
		arg.Memory,
		arg.Error,
		arg.ID,
	)
	return err
}

const getTaskTestCases = `-- name: GetTaskTestCases :many
SELECT id, task_id, case_order, input_file, output_file, created_at, updated_at from task_test_cases WHERE  task_id = $1 ORDER BY case_order
`

func (q *Queries) GetTaskTestCases(ctx context.Context, taskID int32) ([]TaskTestCase, error) {
	rows, err := q.db.Query(ctx, getTaskTestCases, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTestCase
	for rows.Next() {
		var i TaskTestCase
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CaseOrder,
			&i.InputFile,
			&i.OutputFile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestCaseByID = `-- name: GetTestCaseByID :one
SELECT id, task_id, case_order, input_file, output_file, created_at, updated_at from task_test_cases WHERE id = $1
`

func (q *Queries) GetTestCaseByID(ctx context.Context, id int64) (TaskTestCase, error) {
	row := q.db.QueryRow(ctx, getTestCaseByID, id)
	var i TaskTestCase
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CaseOrder,
		&i.InputFile,
		&i.OutputFile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
