// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package db

import (
	"context"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (name)
VALUES ($1) RETURNING id, name, tasks_count, created_at
`

func (q *Queries) CreateTopic(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TasksCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE name = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteTopic, name)
	return err
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, tasks_count, created_at from topics ORDER BY tasks_count DESC
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TasksCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByIDs = `-- name: ListTopicsByIDs :many
SELECT id, name, tasks_count, created_at from topics WHERE id = ANY($1::int[])
`

func (q *Queries) ListTopicsByIDs(ctx context.Context, topicIds []int32) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByIDs, topicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TasksCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topicsByName = `-- name: TopicsByName :many
SELECT id, name, tasks_count, created_at FROM topics WHERE name ILIKE '%' + $1::varchar + '%' ORDER BY tasks_count DESC
`

func (q *Queries) TopicsByName(ctx context.Context, name string) ([]Topic, error) {
	rows, err := q.db.Query(ctx, topicsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TasksCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopicsCounters = `-- name: UpdateTopicsCounters :exec
UPDATE topics SET tasks_count = tasks_count + $1 WHERE id = ANY($2::int[])
`

type UpdateTopicsCountersParams struct {
	Diff     int32   `json:"diff"`
	TopicIds []int32 `json:"topic_ids"`
}

func (q *Queries) UpdateTopicsCounters(ctx context.Context, arg UpdateTopicsCountersParams) error {
	_, err := q.db.Exec(ctx, updateTopicsCounters, arg.Diff, arg.TopicIds)
	return err
}
