// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET roles = -1 WHERE id = $1
`

func (q *Queries) BanUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, banUser, id)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password_hash, roles, elo, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Roles,
		&i.Elo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByEmailOrUsername = `-- name: GetUsersByEmailOrUsername :one
SELECT id, username, email, password_hash, roles, elo, created_at, updated_at FROM users WHERE username = $1 OR email = $1
`

func (q *Queries) GetUsersByEmailOrUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUsersByEmailOrUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Roles,
		&i.Elo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersLeaderboard = `-- name: GetUsersLeaderboard :many
SELECT username, elo from users ORDER BY elo desc limit $1
`

type GetUsersLeaderboardRow struct {
	Username string `json:"username"`
	Elo      int32  `json:"elo"`
}

func (q *Queries) GetUsersLeaderboard(ctx context.Context, limit int32) ([]GetUsersLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getUsersLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersLeaderboardRow
	for rows.Next() {
		var i GetUsersLeaderboardRow
		if err := rows.Scan(&i.Username, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const increaseUserElo = `-- name: IncreaseUserElo :exec
UPDATE users SET elo = elo + $1 WHERE id = $2
`

type IncreaseUserEloParams struct {
	Elo int32 `json:"elo"`
	ID  int32 `json:"id"`
}

func (q *Queries) IncreaseUserElo(ctx context.Context, arg IncreaseUserEloParams) error {
	_, err := q.db.Exec(ctx, increaseUserElo, arg.Elo, arg.ID)
	return err
}

const newUser = `-- name: NewUser :one
INSERT INTO users (username, email, password_hash, elo) VALUES ($1, $2, $3, $4) RETURNING id, username, email, password_hash, roles, elo, created_at, updated_at
`

type NewUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Elo          int32  `json:"elo"`
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, newUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Elo,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Roles,
		&i.Elo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET roles = $1 WHERE id = $2
`

type UpdateUserRoleParams struct {
	Roles int32 `json:"roles"`
	ID    int32 `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Roles, arg.ID)
	return err
}
