/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApierrorApi
 */
export interface ApierrorApi {
    /**
     * 
     * @type {string}
     * @memberof ApierrorApi
     */
    error?: string;
}

/**
 * Check if a given object implements the ApierrorApi interface.
 */
export function instanceOfApierrorApi(value: object): value is ApierrorApi {
    return true;
}

export function ApierrorApiFromJSON(json: any): ApierrorApi {
    return ApierrorApiFromJSONTyped(json, false);
}

export function ApierrorApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApierrorApi {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ApierrorApiToJSON(json: any): ApierrorApi {
    return ApierrorApiToJSONTyped(json, false);
}

export function ApierrorApiToJSONTyped(value?: ApierrorApi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

