/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApierrorApiError
 */
export interface ApierrorApiError {
    /**
     * 
     * @type {number}
     * @memberof ApierrorApiError
     */
    code?: number;
    /**
     * 
     * @type {object}
     * @memberof ApierrorApiError
     */
    error?: object;
}

/**
 * Check if a given object implements the ApierrorApiError interface.
 */
export function instanceOfApierrorApiError(value: object): value is ApierrorApiError {
    return true;
}

export function ApierrorApiErrorFromJSON(json: any): ApierrorApiError {
    return ApierrorApiErrorFromJSONTyped(json, false);
}

export function ApierrorApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApierrorApiError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ApierrorApiErrorToJSON(json: any): ApierrorApiError {
    return ApierrorApiErrorToJSONTyped(json, false);
}

export function ApierrorApiErrorToJSONTyped(value?: ApierrorApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
    };
}

