/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PgtypeInt4 } from './PgtypeInt4';
import {
    PgtypeInt4FromJSON,
    PgtypeInt4FromJSONTyped,
    PgtypeInt4ToJSON,
    PgtypeInt4ToJSONTyped,
} from './PgtypeInt4';
import type { PgtypeText } from './PgtypeText';
import {
    PgtypeTextFromJSON,
    PgtypeTextFromJSONTyped,
    PgtypeTextToJSON,
    PgtypeTextToJSONTyped,
} from './PgtypeText';
import type { PgtypeTimestamp } from './PgtypeTimestamp';
import {
    PgtypeTimestampFromJSON,
    PgtypeTimestampFromJSONTyped,
    PgtypeTimestampToJSON,
    PgtypeTimestampToJSONTyped,
} from './PgtypeTimestamp';

/**
 * 
 * @export
 * @interface DbAttempt
 */
export interface DbAttempt {
    /**
     * 
     * @type {number}
     * @memberof DbAttempt
     */
    attemptStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof DbAttempt
     */
    code?: string;
    /**
     * 
     * @type {PgtypeTimestamp}
     * @memberof DbAttempt
     */
    createdAt?: PgtypeTimestamp;
    /**
     * 
     * @type {PgtypeText}
     * @memberof DbAttempt
     */
    error?: PgtypeText;
    /**
     * 
     * @type {number}
     * @memberof DbAttempt
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DbAttempt
     */
    languageId?: number;
    /**
     * 
     * @type {PgtypeInt4}
     * @memberof DbAttempt
     */
    memory?: PgtypeInt4;
    /**
     * 
     * @type {PgtypeInt4}
     * @memberof DbAttempt
     */
    runningTime?: PgtypeInt4;
    /**
     * 
     * @type {number}
     * @memberof DbAttempt
     */
    taskId?: number;
    /**
     * 
     * @type {PgtypeTimestamp}
     * @memberof DbAttempt
     */
    updatedAt?: PgtypeTimestamp;
    /**
     * 
     * @type {number}
     * @memberof DbAttempt
     */
    userId?: number;
}

/**
 * Check if a given object implements the DbAttempt interface.
 */
export function instanceOfDbAttempt(value: object): value is DbAttempt {
    return true;
}

export function DbAttemptFromJSON(json: any): DbAttempt {
    return DbAttemptFromJSONTyped(json, false);
}

export function DbAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbAttempt {
    if (json == null) {
        return json;
    }
    return {
        
        'attemptStatus': json['attempt_status'] == null ? undefined : json['attempt_status'],
        'code': json['code'] == null ? undefined : json['code'],
        'createdAt': json['created_at'] == null ? undefined : PgtypeTimestampFromJSON(json['created_at']),
        'error': json['error'] == null ? undefined : PgtypeTextFromJSON(json['error']),
        'id': json['id'] == null ? undefined : json['id'],
        'languageId': json['language_id'] == null ? undefined : json['language_id'],
        'memory': json['memory'] == null ? undefined : PgtypeInt4FromJSON(json['memory']),
        'runningTime': json['running_time'] == null ? undefined : PgtypeInt4FromJSON(json['running_time']),
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'updatedAt': json['updated_at'] == null ? undefined : PgtypeTimestampFromJSON(json['updated_at']),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function DbAttemptToJSON(json: any): DbAttempt {
    return DbAttemptToJSONTyped(json, false);
}

export function DbAttemptToJSONTyped(value?: DbAttempt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempt_status': value['attemptStatus'],
        'code': value['code'],
        'created_at': PgtypeTimestampToJSON(value['createdAt']),
        'error': PgtypeTextToJSON(value['error']),
        'id': value['id'],
        'language_id': value['languageId'],
        'memory': PgtypeInt4ToJSON(value['memory']),
        'running_time': PgtypeInt4ToJSON(value['runningTime']),
        'task_id': value['taskId'],
        'updated_at': PgtypeTimestampToJSON(value['updatedAt']),
        'user_id': value['userId'],
    };
}

