/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DbGetUsersLeaderboardRow
 */
export interface DbGetUsersLeaderboardRow {
    /**
     * 
     * @type {number}
     * @memberof DbGetUsersLeaderboardRow
     */
    elo?: number;
    /**
     * 
     * @type {string}
     * @memberof DbGetUsersLeaderboardRow
     */
    username?: string;
}

/**
 * Check if a given object implements the DbGetUsersLeaderboardRow interface.
 */
export function instanceOfDbGetUsersLeaderboardRow(value: object): value is DbGetUsersLeaderboardRow {
    return true;
}

export function DbGetUsersLeaderboardRowFromJSON(json: any): DbGetUsersLeaderboardRow {
    return DbGetUsersLeaderboardRowFromJSONTyped(json, false);
}

export function DbGetUsersLeaderboardRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbGetUsersLeaderboardRow {
    if (json == null) {
        return json;
    }
    return {
        
        'elo': json['elo'] == null ? undefined : json['elo'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function DbGetUsersLeaderboardRowToJSON(json: any): DbGetUsersLeaderboardRow {
    return DbGetUsersLeaderboardRowToJSONTyped(json, false);
}

export function DbGetUsersLeaderboardRowToJSONTyped(value?: DbGetUsersLeaderboardRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elo': value['elo'],
        'username': value['username'],
    };
}

