/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PgtypeTimestamp } from './PgtypeTimestamp';
import {
    PgtypeTimestampFromJSON,
    PgtypeTimestampFromJSONTyped,
    PgtypeTimestampToJSON,
    PgtypeTimestampToJSONTyped,
} from './PgtypeTimestamp';

/**
 * 
 * @export
 * @interface DbTaskTestCase
 */
export interface DbTaskTestCase {
    /**
     * 
     * @type {number}
     * @memberof DbTaskTestCase
     */
    caseOrder?: number;
    /**
     * 
     * @type {PgtypeTimestamp}
     * @memberof DbTaskTestCase
     */
    createdAt?: PgtypeTimestamp;
    /**
     * 
     * @type {number}
     * @memberof DbTaskTestCase
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DbTaskTestCase
     */
    inputFile?: string;
    /**
     * 
     * @type {string}
     * @memberof DbTaskTestCase
     */
    outputFile?: string;
    /**
     * 
     * @type {number}
     * @memberof DbTaskTestCase
     */
    taskId?: number;
    /**
     * 
     * @type {PgtypeTimestamp}
     * @memberof DbTaskTestCase
     */
    updatedAt?: PgtypeTimestamp;
}

/**
 * Check if a given object implements the DbTaskTestCase interface.
 */
export function instanceOfDbTaskTestCase(value: object): value is DbTaskTestCase {
    return true;
}

export function DbTaskTestCaseFromJSON(json: any): DbTaskTestCase {
    return DbTaskTestCaseFromJSONTyped(json, false);
}

export function DbTaskTestCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbTaskTestCase {
    if (json == null) {
        return json;
    }
    return {
        
        'caseOrder': json['case_order'] == null ? undefined : json['case_order'],
        'createdAt': json['created_at'] == null ? undefined : PgtypeTimestampFromJSON(json['created_at']),
        'id': json['id'] == null ? undefined : json['id'],
        'inputFile': json['input_file'] == null ? undefined : json['input_file'],
        'outputFile': json['output_file'] == null ? undefined : json['output_file'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'updatedAt': json['updated_at'] == null ? undefined : PgtypeTimestampFromJSON(json['updated_at']),
    };
}

export function DbTaskTestCaseToJSON(json: any): DbTaskTestCase {
    return DbTaskTestCaseToJSONTyped(json, false);
}

export function DbTaskTestCaseToJSONTyped(value?: DbTaskTestCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'case_order': value['caseOrder'],
        'created_at': PgtypeTimestampToJSON(value['createdAt']),
        'id': value['id'],
        'input_file': value['inputFile'],
        'output_file': value['outputFile'],
        'task_id': value['taskId'],
        'updated_at': PgtypeTimestampToJSON(value['updatedAt']),
    };
}

