/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DbUpdateTaskParams
 */
export interface DbUpdateTaskParams {
    /**
     * 
     * @type {string}
     * @memberof DbUpdateTaskParams
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof DbUpdateTaskParams
     */
    difficulty?: number;
    /**
     * 
     * @type {number}
     * @memberof DbUpdateTaskParams
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DbUpdateTaskParams
     */
    passes?: number;
    /**
     * 
     * @type {number}
     * @memberof DbUpdateTaskParams
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof DbUpdateTaskParams
     */
    title?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof DbUpdateTaskParams
     */
    topics?: Array<number>;
}

/**
 * Check if a given object implements the DbUpdateTaskParams interface.
 */
export function instanceOfDbUpdateTaskParams(value: object): value is DbUpdateTaskParams {
    return true;
}

export function DbUpdateTaskParamsFromJSON(json: any): DbUpdateTaskParams {
    return DbUpdateTaskParamsFromJSONTyped(json, false);
}

export function DbUpdateTaskParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbUpdateTaskParams {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'id': json['id'] == null ? undefined : json['id'],
        'passes': json['passes'] == null ? undefined : json['passes'],
        'score': json['score'] == null ? undefined : json['score'],
        'title': json['title'] == null ? undefined : json['title'],
        'topics': json['topics'] == null ? undefined : json['topics'],
    };
}

export function DbUpdateTaskParamsToJSON(json: any): DbUpdateTaskParams {
    return DbUpdateTaskParamsToJSONTyped(json, false);
}

export function DbUpdateTaskParamsToJSONTyped(value?: DbUpdateTaskParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'difficulty': value['difficulty'],
        'id': value['id'],
        'passes': value['passes'],
        'score': value['score'],
        'title': value['title'],
        'topics': value['topics'],
    };
}

