/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PgtypeTimestamp } from './PgtypeTimestamp';
import {
    PgtypeTimestampFromJSON,
    PgtypeTimestampFromJSONTyped,
    PgtypeTimestampToJSON,
    PgtypeTimestampToJSONTyped,
} from './PgtypeTimestamp';

/**
 * 
 * @export
 * @interface DbUser
 */
export interface DbUser {
    /**
     * 
     * @type {PgtypeTimestamp}
     * @memberof DbUser
     */
    createdAt?: PgtypeTimestamp;
    /**
     * 
     * @type {number}
     * @memberof DbUser
     */
    elo?: number;
    /**
     * 
     * @type {string}
     * @memberof DbUser
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof DbUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DbUser
     */
    passwordHash?: string;
    /**
     * 
     * @type {number}
     * @memberof DbUser
     */
    roles?: number;
    /**
     * 
     * @type {PgtypeTimestamp}
     * @memberof DbUser
     */
    updatedAt?: PgtypeTimestamp;
    /**
     * 
     * @type {string}
     * @memberof DbUser
     */
    username?: string;
}

/**
 * Check if a given object implements the DbUser interface.
 */
export function instanceOfDbUser(value: object): value is DbUser {
    return true;
}

export function DbUserFromJSON(json: any): DbUser {
    return DbUserFromJSONTyped(json, false);
}

export function DbUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbUser {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : PgtypeTimestampFromJSON(json['created_at']),
        'elo': json['elo'] == null ? undefined : json['elo'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'passwordHash': json['password_hash'] == null ? undefined : json['password_hash'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'updatedAt': json['updated_at'] == null ? undefined : PgtypeTimestampFromJSON(json['updated_at']),
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function DbUserToJSON(json: any): DbUser {
    return DbUserToJSONTyped(json, false);
}

export function DbUserToJSONTyped(value?: DbUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': PgtypeTimestampToJSON(value['createdAt']),
        'elo': value['elo'],
        'email': value['email'],
        'id': value['id'],
        'password_hash': value['passwordHash'],
        'roles': value['roles'],
        'updated_at': PgtypeTimestampToJSON(value['updatedAt']),
        'username': value['username'],
    };
}

