/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateTaskDTO
 */
export interface ModelsCreateTaskDTO {
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateTaskDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateTaskDTO
     */
    difficulty?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateTaskDTO
     */
    title?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ModelsCreateTaskDTO
     */
    topics?: Array<number>;
}

/**
 * Check if a given object implements the ModelsCreateTaskDTO interface.
 */
export function instanceOfModelsCreateTaskDTO(value: object): value is ModelsCreateTaskDTO {
    return true;
}

export function ModelsCreateTaskDTOFromJSON(json: any): ModelsCreateTaskDTO {
    return ModelsCreateTaskDTOFromJSONTyped(json, false);
}

export function ModelsCreateTaskDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateTaskDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'title': json['title'] == null ? undefined : json['title'],
        'topics': json['topics'] == null ? undefined : json['topics'],
    };
}

export function ModelsCreateTaskDTOToJSON(json: any): ModelsCreateTaskDTO {
    return ModelsCreateTaskDTOToJSONTyped(json, false);
}

export function ModelsCreateTaskDTOToJSONTyped(value?: ModelsCreateTaskDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'difficulty': value['difficulty'],
        'title': value['title'],
        'topics': value['topics'],
    };
}

