/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsAuthUserDTO
 */
export interface ModelsAuthUserDTO {
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthUserDTO
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthUserDTO
     */
    password: string;
}

/**
 * Check if a given object implements the ModelsAuthUserDTO interface.
 */
export function instanceOfModelsAuthUserDTO(value: object): value is ModelsAuthUserDTO {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ModelsAuthUserDTOFromJSON(json: any): ModelsAuthUserDTO {
    return ModelsAuthUserDTOFromJSONTyped(json, false);
}

export function ModelsAuthUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsAuthUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'password': json['password'],
    };
}

export function ModelsAuthUserDTOToJSON(json: any): ModelsAuthUserDTO {
    return ModelsAuthUserDTOToJSONTyped(json, false);
}

export function ModelsAuthUserDTOToJSONTyped(value?: ModelsAuthUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'password': value['password'],
    };
}

