/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsNewTestCaseReq
 */
export interface ModelsNewTestCaseReq {
    /**
     * 
     * @type {number}
     * @memberof ModelsNewTestCaseReq
     */
    taskId?: number;
}

/**
 * Check if a given object implements the ModelsNewTestCaseReq interface.
 */
export function instanceOfModelsNewTestCaseReq(value: object): value is ModelsNewTestCaseReq {
    return true;
}

export function ModelsNewTestCaseReqFromJSON(json: any): ModelsNewTestCaseReq {
    return ModelsNewTestCaseReqFromJSONTyped(json, false);
}

export function ModelsNewTestCaseReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsNewTestCaseReq {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
    };
}

export function ModelsNewTestCaseReqToJSON(json: any): ModelsNewTestCaseReq {
    return ModelsNewTestCaseReqToJSONTyped(json, false);
}

export function ModelsNewTestCaseReqToJSONTyped(value?: ModelsNewTestCaseReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
    };
}

