/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateUserDTO
 */
export interface ModelsCreateUserDTO {
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateUserDTO
     */
    email: string;
    /**
     * Basic validation example
     * @type {string}
     * @memberof ModelsCreateUserDTO
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateUserDTO
     */
    username: string;
}

/**
 * Check if a given object implements the ModelsCreateUserDTO interface.
 */
export function instanceOfModelsCreateUserDTO(value: object): value is ModelsCreateUserDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ModelsCreateUserDTOFromJSON(json: any): ModelsCreateUserDTO {
    return ModelsCreateUserDTOFromJSONTyped(json, false);
}

export function ModelsCreateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'username': json['username'],
    };
}

export function ModelsCreateUserDTOToJSON(json: any): ModelsCreateUserDTO {
    return ModelsCreateUserDTOToJSONTyped(json, false);
}

export function ModelsCreateUserDTOToJSONTyped(value?: ModelsCreateUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'username': value['username'],
    };
}

