/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateAttemptRequest
 */
export interface ModelsCreateAttemptRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateAttemptRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateAttemptRequest
     */
    lang?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateAttemptRequest
     */
    taskId?: number;
}

/**
 * Check if a given object implements the ModelsCreateAttemptRequest interface.
 */
export function instanceOfModelsCreateAttemptRequest(value: object): value is ModelsCreateAttemptRequest {
    return true;
}

export function ModelsCreateAttemptRequestFromJSON(json: any): ModelsCreateAttemptRequest {
    return ModelsCreateAttemptRequestFromJSONTyped(json, false);
}

export function ModelsCreateAttemptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateAttemptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'lang': json['lang'] == null ? undefined : json['lang'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
    };
}

export function ModelsCreateAttemptRequestToJSON(json: any): ModelsCreateAttemptRequest {
    return ModelsCreateAttemptRequestToJSONTyped(json, false);
}

export function ModelsCreateAttemptRequestToJSONTyped(value?: ModelsCreateAttemptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'lang': value['lang'],
        'task_id': value['taskId'],
    };
}

