/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PgtypeText
 */
export interface PgtypeText {
    /**
     * 
     * @type {string}
     * @memberof PgtypeText
     */
    string?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PgtypeText
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the PgtypeText interface.
 */
export function instanceOfPgtypeText(value: object): value is PgtypeText {
    return true;
}

export function PgtypeTextFromJSON(json: any): PgtypeText {
    return PgtypeTextFromJSONTyped(json, false);
}

export function PgtypeTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PgtypeText {
    if (json == null) {
        return json;
    }
    return {
        
        'string': json['string'] == null ? undefined : json['string'],
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

export function PgtypeTextToJSON(json: any): PgtypeText {
    return PgtypeTextToJSONTyped(json, false);
}

export function PgtypeTextToJSONTyped(value?: PgtypeText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'string': value['string'],
        'valid': value['valid'],
    };
}

