/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PgtypeInfinityModifier = {
    Infinity: 1,
    Finite: 0,
    NegativeInfinity: -1
} as const;
export type PgtypeInfinityModifier = typeof PgtypeInfinityModifier[keyof typeof PgtypeInfinityModifier];


export function instanceOfPgtypeInfinityModifier(value: any): boolean {
    for (const key in PgtypeInfinityModifier) {
        if (Object.prototype.hasOwnProperty.call(PgtypeInfinityModifier, key)) {
            if (PgtypeInfinityModifier[key as keyof typeof PgtypeInfinityModifier] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PgtypeInfinityModifierFromJSON(json: any): PgtypeInfinityModifier {
    return PgtypeInfinityModifierFromJSONTyped(json, false);
}

export function PgtypeInfinityModifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PgtypeInfinityModifier {
    return json as PgtypeInfinityModifier;
}

export function PgtypeInfinityModifierToJSON(value?: PgtypeInfinityModifier | null): any {
    return value as any;
}

export function PgtypeInfinityModifierToJSONTyped(value: any, ignoreDiscriminator: boolean): PgtypeInfinityModifier {
    return value as PgtypeInfinityModifier;
}

