/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PgtypeInfinityModifier } from './PgtypeInfinityModifier';
import {
    PgtypeInfinityModifierFromJSON,
    PgtypeInfinityModifierFromJSONTyped,
    PgtypeInfinityModifierToJSON,
    PgtypeInfinityModifierToJSONTyped,
} from './PgtypeInfinityModifier';

/**
 * 
 * @export
 * @interface PgtypeTimestamp
 */
export interface PgtypeTimestamp {
    /**
     * 
     * @type {PgtypeInfinityModifier}
     * @memberof PgtypeTimestamp
     */
    infinityModifier?: PgtypeInfinityModifier;
    /**
     * Time zone will be ignored when encoding to PostgreSQL.
     * @type {string}
     * @memberof PgtypeTimestamp
     */
    time?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PgtypeTimestamp
     */
    valid?: boolean;
}



/**
 * Check if a given object implements the PgtypeTimestamp interface.
 */
export function instanceOfPgtypeTimestamp(value: object): value is PgtypeTimestamp {
    return true;
}

export function PgtypeTimestampFromJSON(json: any): PgtypeTimestamp {
    return PgtypeTimestampFromJSONTyped(json, false);
}

export function PgtypeTimestampFromJSONTyped(json: any, ignoreDiscriminator: boolean): PgtypeTimestamp {
    if (json == null) {
        return json;
    }
    return {
        
        'infinityModifier': json['infinityModifier'] == null ? undefined : PgtypeInfinityModifierFromJSON(json['infinityModifier']),
        'time': json['time'] == null ? undefined : json['time'],
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

export function PgtypeTimestampToJSON(json: any): PgtypeTimestamp {
    return PgtypeTimestampToJSONTyped(json, false);
}

export function PgtypeTimestampToJSONTyped(value?: PgtypeTimestamp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'infinityModifier': PgtypeInfinityModifierToJSON(value['infinityModifier']),
        'time': value['time'],
        'valid': value['valid'],
    };
}

