/* tslint:disable */
/* eslint-disable */
/**
 * Rankode
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PgtypeInt4
 */
export interface PgtypeInt4 {
    /**
     * 
     * @type {number}
     * @memberof PgtypeInt4
     */
    int32?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PgtypeInt4
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the PgtypeInt4 interface.
 */
export function instanceOfPgtypeInt4(value: object): value is PgtypeInt4 {
    return true;
}

export function PgtypeInt4FromJSON(json: any): PgtypeInt4 {
    return PgtypeInt4FromJSONTyped(json, false);
}

export function PgtypeInt4FromJSONTyped(json: any, ignoreDiscriminator: boolean): PgtypeInt4 {
    if (json == null) {
        return json;
    }
    return {
        
        'int32': json['int32'] == null ? undefined : json['int32'],
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

export function PgtypeInt4ToJSON(json: any): PgtypeInt4 {
    return PgtypeInt4ToJSONTyped(json, false);
}

export function PgtypeInt4ToJSONTyped(value?: PgtypeInt4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'int32': value['int32'],
        'valid': value['valid'],
    };
}

